apiVersion: v1
kind: Secret
metadata:
  name: {{ include "new-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  SQL_DSN: {{ include "new-api.sqlDsn" . | quote }}
  {{- if .Values.externalDatabase.logDsn }}
  LOG_SQL_DSN: {{ include "new-api.logSqlDsn" . | quote }}
  {{- end }}
  {{- if .Values.redis.external.enabled }}
  REDIS_CONN_STRING: {{ include "new-api.redisConnString" . | quote }}
  {{- end }}
  {{- range $k, $v := .Values.extraSecretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
