apiVersion: v1
kind: Service
metadata:
  name: {{ include "new-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "new-api.selectorLabels" . | nindent 4 }}
